### ISSUE TITLE
Understanding failed ppcOcc tests

### ISSUE THREAD

**Issue by abfleishman** [doserjef/spOccupancy#18]
## Background

I am trying to run the goodness of fit `ppcOcc` on a model fit with `tPGOcc` or `PGOcc`.  My study design is "site limited" with ~40 sites, 20 of which were burned in a fire.  We have acoustic recorders at each site recording all year with some gaps. we have 2 years of data. Currently, I am trying to bin detection vs non-detection at a daily scale for each season (summer, winter, etc) so I have ~90 replicate surveys at each site each season in each year.    I am hoping to use detection histories built with predictions from either BirdNET or a custom detection model.  Below I use Rock Wren and BirdNET 

I am an ecologist and I am proficient with R, but this is my first time working with occupancy models.  

## Detection History

For this species, they were not detected in the burned habitat. But I get the same issues I document below with other species that are found in both habitats.

![image](https://user-images.githubusercontent.com/9219852/221027453-cd66bb8e-8ea1-42ee-a1e2-678b75863c41.png)

## Model
I set up my data link in the tutorial. There are a bunch of covars I am not using (yet) because I wanted to start simple.

### data prep
```r
str(spT_tidy)
List of 4
 $ y       : num [1:36, 1:2, 1:184] NA NA NA NA NA NA NA NA NA NA ...
  ..- attr(*, "dimnames")=List of 3
  .. ..$ : chr [1:36] "AUBO8" "AUBP7" "AUBP8" "AUM10" ...
  .. ..$ : chr [1:2] "2021" "2022"
  .. ..$ : chr [1:184] "60" "61" "62" "63" ...
 $ occ.covs:List of 5
  ..$ site       : chr [1:36] "AUBO8" "AUBP7" "AUBP8" "AUM10" ...
  ..$ site_effect: num [1:36, 1:2] 1 2 3 4 5 6 7 8 9 10 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : NULL
  .. .. ..$ : chr [1:2] "X2021" "X2022"
  ..$ year       : int [1:36, 1:2] 2021 2021 2021 2021 2021 2021 2021 2021 2021 2021 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : NULL
  .. .. ..$ : chr [1:2] "2021" "2022"
  ..$ year_fact  : Factor w/ 2 levels "2021","2022": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ fire       : chr [1:36, 1:2] "burned" "burned" "burned" "burned" ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : NULL
  .. .. ..$ : chr [1:2] "X2021" "X2022"
 $ det.covs:List of 4
  ..$ year  : int [1:36, 1:2, 1:184] NA NA NA NA NA NA NA NA NA NA ...
  .. ..- attr(*, "dimnames")=List of 3
  .. .. ..$ : chr [1:36] "AUBO8" "AUBP7" "AUBP8" "AUM10" ...
  .. .. ..$ : chr [1:2] "2021" "2022"
  .. .. ..$ : chr [1:184] "60" "61" "62" "63" ...
  ..$ fire  : chr [1:36, 1:2, 1:184] NA NA NA NA ...
  .. ..- attr(*, "dimnames")=List of 3
  .. .. ..$ : chr [1:36] "AUBO8" "AUBP7" "AUBP8" "AUM10" ...
  .. .. ..$ : chr [1:2] "2021" "2022"
  .. .. ..$ : chr [1:184] "60" "61" "62" "63" ...
  ..$ effort: int [1:36, 1:2, 1:184] NA NA NA NA NA NA NA NA NA NA ...
  .. ..- attr(*, "dimnames")=List of 3
  .. .. ..$ : chr [1:36] "AUBO8" "AUBP7" "AUBP8" "AUM10" ...
  .. .. ..$ : chr [1:2] "2021" "2022"
  .. .. ..$ : chr [1:184] "60" "61" "62" "63" ...
  ..$ doy   : num [1:36, 1:2, 1:184] 60 60 60 60 60 60 60 60 60 60 ...
  .. ..- attr(*, "dimnames")=List of 3
  .. .. ..$ : chr [1:36] "AUBO8" "AUBP7" "AUBP8" "AUM10" ...
  .. .. ..$ : chr [1:2] "2021" "2022"
  .. .. ..$ : chr [1:184] "60" "61" "62" "63" ...
 $ coords  : num [1:36, 1:2] 606864 607327 607392 605894 605864 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:36] "1" "2" "3" "4" ...
  .. ..$ : chr [1:2] "X" "Y"
  ```

## Model

```r
    z.inits <- apply(spT_tidy$y, c(1,2), function(a) as.numeric(sum(a, na.rm = TRUE) > 0))

   spT_tidy.inits <- list(beta = 0,         # occurrence coefficients
                           alpha = 0,        # detection coefficients
                           sigma.sq.psi = 1, # occurrence random effect variances
                           z = z.inits)      # latent occurrence values
    spT_tidy.priors <- list(beta.normal = list(mean = 0, var = 2.72), 
                            alpha.normal = list(mean = 0, var = 2.72), 
                            sigma.sq.psi.ig = list(a = 0.1, b = 0.1))
    
    n.chains <- 4
    n.batch <- 200
    batch.length <- 25
    n.samples <- n.batch * batch.length 
    n.burn <- 2000
    n.thin <- 12
    ar1 <- T

out1 <- tPGOcc(occ.formula = ~1+fire, 
                       det.formula = ~1, 
                       data = spT_tidy, 
                       n.batch = n.batch, 
                       batch.length = batch.length,
                       inits = spT_tidy.inits,
                       priors = spT_tidy.priors,
                       ar1 = ar1,
                       n.burn = n.burn, 
                       n.thin = n.thin, 
                       n.chains = n.chains, 
                       n.report = 50)
```

As you can see below the model appears to fit well with r-hat small and decent ESS. 

```r
summary(out1)

Call:
tPGOcc(occ.formula = ~1 + fire, det.formula = ~1, data = spT_tidy, inits = spT_tidy.inits, priors = spT_tidy.priors, 
    n.batch = n.batch, batch.length = batch.length, ar1 = ar1, n.report = 50, n.burn = n.burn, n.thin = n.thin, 
    n.chains = n.chains)

Samples per Chain: 5000
Burn-in: 2000
Thinning Rate: 12
Number of Chains: 4
Total Posterior Samples: 1000
Run Time (min): 0.2473

Occurrence (logit scale): 
                Mean     SD    2.5%    50%   97.5%   Rhat  ESS
(Intercept)  -2.9721 0.8180 -4.5438 -2.947 -1.3392 1.0016 1000
fireunburned  1.6992 0.8139  0.1448  1.642  3.4134 1.0028 1000

Detection (logit scale): 
               Mean     SD    2.5%     50%   97.5%  Rhat  ESS
(Intercept) -1.3741 0.1058 -1.5853 -1.3762 -1.1697 1.001 1000

Occurrence AR(1) Temporal Covariance: 
             Mean     SD    2.5%    50%  97.5%  Rhat  ESS
sigma.sq.t 0.4027 0.4358  0.0866 0.2795 1.4350 1.005 1000
rho        0.1183 0.5819 -0.9326 0.1766 0.9611 1.004  887
```

## ppcOcc with group = 1

I have been able to run  `PGOcc` on a single year of data and `tPGOcc` on the 2-year datasets for a bunch of species, but for every single one I am seeing terrible GoF stats when run `ppcOcc` with `group = 1`  (Bayes p = 0.0 ).

``` r
    ppc.out1_sites <- ppcOcc(out1, fit.stat = 'freeman-tukey', group = 1)
    summary(ppc.out1_sites)


Call:
ppcOcc(object = out1, fit.stat = "freeman-tukey", group = 1)

Samples per Chain: 5000
Burn-in: 2000
Thinning Rate: 12
Number of Chains: 4
Total Posterior Samples: 1000

----------------------------------------
	All time periods combined
----------------------------------------
Bayesian p-value:  0 

----------------------------------------
	Individual time periods
----------------------------------------
Time Period 1 Bayesian p-value: 0
Time Period 2 Bayesian p-value: 0
Fit statistic:  freeman-tukey 
```

When I make the fit plots that you use in your example they show that the scales of the fit vs the scale of the "true" are really different.  
![image](https://user-images.githubusercontent.com/9219852/221025232-dbb39cc2-de2e-45c7-a0a5-518fa215debf.png)

and that the `replicate - true discrepancy` is always negative with a few sites with big negative numbers.  

![image](https://user-images.githubusercontent.com/9219852/221025475-cc7bc270-beaa-4af6-b030-1e8fd1743c24.png)

## ppcOcc with group = 2

This seems to work better but one of the years gets a very high Bayes p (0.99)  

``` r
    ppc.out1_replicates <- ppcOcc(out1, fit.stat = 'freeman-tukey', group = 2)
    summary(ppc.out1_replicates)

Call:
ppcOcc(object = out1, fit.stat = "freeman-tukey", group = 2)

Samples per Chain: 5000
Burn-in: 2000
Thinning Rate: 12
Number of Chains: 4
Total Posterior Samples: 1000

----------------------------------------
	All time periods combined
----------------------------------------
Bayesian p-value:  0.8015 

----------------------------------------
	Individual time periods
----------------------------------------
Time Period 1 Bayesian p-value: 0.612
Time Period 2 Bayesian p-value: 0.991
Fit statistic:  freeman-tukey 
```
These are from time period 2 with the high bayes p. 
![image](https://user-images.githubusercontent.com/9219852/221026065-6cf78ff4-1cee-4495-8b35-361385af0bf0.png)

![image](https://user-images.githubusercontent.com/9219852/221026353-cfb74a52-8bf3-4219-8e5f-048843cfb966.png)

## My Question...
 Inspecting the occupancy estimate from the model shows patterns that I would expect.

![image](https://user-images.githubusercontent.com/9219852/221026881-77f76f18-e65c-4dce-89d4-88aaefc88c6a.png)

My ideas:
-  There are not enough sites in each treatment (burned/unburned) to fit these models?  
- There are too many replicates to use this approach (unmarked fit this dataset decently, but only using year 1)?
- I am misspecifying something or failing to standardize a variable that is causing chaos?

It is clear from the ppc checks that there is something about the model that is "unhappy".  But I am a bit at a loss of what to do next?  What diagnostics should I look at or what would the steps for troubleshooting this be?

I am not really sure how to "fix" the model so it passes the `ppcOcc` tests? Any ideas? 

Lastly, the model produces occupancy estimates that I think are reasonable.  Is there a world where I could decide to ignore the tests and use the model as is without risking the stats-gods' revenge?

**Comment by abfleishman** [comment]
@doserjef  Thank you for your thoughtful replies!  Everything you said makes sense, and just last night I started to add other covariates but many of the models errored.  I have not looked into the errors yet but will open another issue if I think it is worth asking about them.  

> You currently have ar1 = TRUE, which means you're estimating an AR(1) temporal random effect

If I leave `ar1 = F`, what happens with the 2 years of data in the model?  Seems like I would need to include `year`  as a fixed effect in the model?  If I am not using the `AR(1)` or including `year` in the model, should I be using `PGOcc` instead of `tPGOcc`?

> The always bad p-values indicates that there is additional variation in occupancy probability and/or detection probability that the model is not accounting for. This suggests you need to add in additional covariates and/or random effects to account for this variability.

This makes some sense to me: my frequentist brain says the current model has a small R^2 value and thus little ecological explanatory power.  I guess I am a little confused why that "extra" variance (the variance that other covariates _would_ explain) is not just absorbed into the estimates of occupancy and detection probability, giving them very large credible intervals?  The credible intervals seem reasonably tight.  I guess I would expect a poorly fitting model to give a lot of uncertainty in the parameter estimates and just reduce your power to detect differences or relationships.

**Comment by doserjef** [comment]
@abfleishman yes, including year as a fixed effect is a reasonable option for this case with only two years of data. Yes, you could technically use `tPGOcc()` or `PGOcc()` to fit the model if you're not using the `AR(1)` component and it will give you the same results as `PGOcc()`, you'll just have to format the data slightly differently. If you try to account for spatial autocorrelation, you'll need the `stPGOcc()` function, as `spPGOcc()` won't work with multiple years of data. 

As far as your comment on large credible intervals, the width of the credible intervals is not directly tied to how well the model accurately represents the data. There are many cases in which a model can fit, have reasonable credible intervals, and not be a good model. For example, if a model has spatial autocorrelation that is not accounted for, the estimates will be overly precise and the credible intervals will actually be too narrow. Part of what you're seeing is related to the fact that a Bernoulli distribution that is used for binary data has a single parameter (i.e., probability of detection or probability of occupancy). Unlike in a basic linear model, there is no additional variance parameter that can soak up unexplained variation.

**Comment by abfleishman** [comment]
> yes, including year as a fixed effect is a reasonable option for this case with only two years of data. 

Ok good.  I think that will be my plan as we are going to be collecting data for several years and eventually we will want to check for trends.  Sounds easier to set things up to allow that from the start.

> Part of what you're seeing is related to the fact that a Bernoulli distribution that is used for binary data has a single parameter (i.e., probability of detection or probability of occupancy). **Unlike in a basic linear model, there is no additional variance parameter that can soak up unexplained variation.**

Woah.... do you have any resources off the top of your head that addresses this idea? I am coming from a GLMM background and this is a new concept for me.

**Comment by doserjef** [comment]
I don't have any large resources specifically off the top of my head, but this concept is similar to overdispersion, which is a common phenomenon in GLMs. For example, if you have count data that is widely overdispersed, you can fit a Poisson GLM to it and probably get estimates that have high precision. However, because the Poisson restricts the mean to equal the variance (i.e., there is no separate variance parameter), the model likely is not a good representation of the true variability in the data. Here's a [short resource](https://online.stat.psu.edu/stat504/book/export/html/779) I found just by some quick googling

**Comment by abfleishman** [comment]
Ok that comparison makes sense to me.  Thank you.  I think we can close this issue.
