### ISSUE TITLE
Guidance on comparing levels of a factor included in a model

### ISSUE THREAD

**Issue by abfleishman** [doserjef/spOccupancy#19]
## Background

I am trying to use occupancy as a measure to compare treatments in a CA park.  The variable of interest in `fire` with two levels: `unburned` and `burned`.  I want to compare the estimated difference in occupancy between the two levels and see if it is different from 0.

See #18 for more background about the type of model.

Here is the estimated occupancy for one of the species (Rock Wren) 

![image](https://user-images.githubusercontent.com/9219852/221026881-77f76f18-e65c-4dce-89d4-88aaefc88c6a.png)

## Comparing levels

For a model `m` with `fire` as the only predictor, I am using `tidybayes::spread_draws` and `tidybayes::compare_levels` to calculate the difference for each draw.  I am doing this on the non-back-transformed logit scale.  For this example, (Rock Wren) it finds a difference with `burned` higher than `unburned`.  Does this seem like the correct approach?  Should I be doing this after back transforming somehow (probably a dumb question)?

 I would love to use a package like `marginaleffects` or `emmeans` to do this analysis and understand that is a large dev request but figured I would put it out there. 

```r
m$beta.samples %>%
    tidybayes::spread_draws(`(Intercept)`,fireunburned) %>%
    mutate(Burned = `(Intercept)`, Unburned = `(Intercept)`+fireunburned) %>%
    select(-fireunburned,-`(Intercept)`) %>%
    tidyr::gather(key = fire,value= .value, Burned:Unburned) %>%
    tidybayes::compare_levels(data = .,variable = .value,by=fire,comparison = control) 
```
![image](https://user-images.githubusercontent.com/9219852/221032817-335a9583-75cc-4ca7-9171-69471447af42.png)

**Comment by abfleishman** [comment]
>  if you fit the model with a means parameterization such that a separate intercept was estimated for burned and unburned, then to calculate the difference, you can just take the difference between the two columns in the m$beta.samples object.

Ok I think this is what I am doing.  But with my simple model with `fire` as the only predictor (with 2 levels burned vs unburned, the  m$beta.samples data frame has two columns, `(intercept)` and  `fireunburned`.  I am assuming in this case that the intercept represents `burned`. I guess my remaining question is: as I add more variables to my model, and the intercept begins to represent more than the one level of the fire variable (i.e. it also represents year one if the formula were `~1+year+fire`), what is the appropriate way to calculate the marginal means for the levels of the fire variable? I think I am using the correct vocabulary.

**Comment by doserjef** [comment]
Okay, so the parameterization you currently have then is an effects parameterization, such that `m$beta.samples[, 1]` represents the mean occupancy in burned sites, and `m$beta.samples[, 2]` is the difference in occupancy between burned and unburned sites. To get the mean in unburned sites, you would just do `m$beta.samples[, 1] + m$beta.samples[, 2]`. 

If you add in another categorical variable like `year`, then the intercept in that case would be the mean occupancy in burned sites in the first year. Assuming there are two levels of year (just say 2021 and 2022 for simplicity) and two levels of fire (burned and unburned), you can extract the means as follows from the `m$beta.samples` object (note that depending on how things are coded the column names in `m$beta.samples` may be slightly different):

```
# Burned in year 2021
burn.2021.samples <- m$beta.samples[, '(Intercept)']
# Burned in year 2022
burned.2022.samples <- m$beta.samples[, '(Intercept)'] + m $beta.samples[, 'year2021']
# Unburned in year 2021
unburned.2021.samples <- m$beta.samples[, '(Intercept)'] + m$beta.samples[, 'fireunburned']
# Unburned in year 2022
unburned.2022.samples <- m$beta.samples[, '(Intercept)'] + m$beta.samples[, 'fireunburned'] + m$beta.samples[, 'year2021']
```

**Comment by abfleishman** [comment]
Ok perfect!  That is what I was hoping.  Thank you!
