### ISSUE TITLE
Guidance on comparing levels of 2 factors with an interaction 

### ISSUE THREAD

**Issue by abfleishman** [doserjef/spOccupancy#20]
As an extension of #19, we have a different project where we have before/after control/impact design (BACI).  We will want to ask is the change from before to after is different in the control vs the treatment.  I am unclear how I would do this type of contrast with the resulting models with `spOccupancy`.  

Do you have any thoughts/insights that would help me get started?  

(Sorry for asking such a vague question)

**Comment by doserjef** [comment]
Hi again @abfleishman!

I'm not all that familiar with a BACI design, so I unfortunately don't have any specific suggestions as to how to implement this. In the [paper linked here](https://zipkinlab.org/wp-content/uploads/2021/11/Cabodevilla-et-al.-2022_AEE.pdf), they fit a multi-species occupancy model (not with `spOccupancy`) for a BACI design, which might be helpful for you thinking about how to go about doing your analysis. I'll say that interactions can be included in the `spOccupancy` formulas just as you would include them in other packages that use R's formula interface. Once you start fitting the model, if you have more specific questions then feel free to email me with the questions and code/data and I can try to play around with it to help out more (my email is doserjef@msu.edu). 

Sorry for not having more specific thoughts on this!

Jeff

**Comment by abfleishman** [comment]
Thanks Jeff,

I will like ly be in touch via email.  

-Abram
