### ISSUE TITLE
Error Code - BLAS/LAPACK routine 'DGEMV DGER  DSBMV DS' gave error code -6

### ISSUE THREAD

**Issue by AndrewCSlater** [doserjef/spOccupancy#23]
Hi I am just strating to try this package out and came across this error when trying to run a single species occupancy model.

Error in PGOcc(occ.formula = oven.occ.formula, det.formula = oven.det.formula,  : 
  BLAS/LAPACK routine 'DGEMV DGER  DSBMV DS' gave error code -6

The occ formula is ~1
The det formula is a single variable as a matrix

Please let me know if you need more info.

Thanks!
Andrew

**Comment by doserjef** [comment]
Hi Andrew, 

Thanks for the note. That error indicates there is something going on in the underlying MCMC sampler.  I am not able to reproduce the error with a simulated data set with the same types of variables in the formulas, so I'm thinking it might be some formatting issue. Can you email me (doserjef@msu.edu) a script and the associated data that's giving you the problem and I'll take a look to try to see what's going on?

Thanks,

Jeff

**Comment by doserjef** [comment]
This issue was a result of problems with data formatting, not with the underlying package.
