### ISSUE TITLE
.doSnowGlobals not found

### ISSUE THREAD

**Issue by swbigelow** [doserjef/spOccupancy#32]
I am working through the Hubbard Brook tutorial. When I run spPFOcc(), I get error "Error in checkForRemoteErrors(lapply(cl, recvResult)) : one node produced an error: object '.doSnowGlobals' not found". I understand from StackOverflow that this is a parallel computing issue-somehow the cores are not getting the information they need. I have tried installing 'doSNOW' and 'doParallel' packages, and various ways of passing the location of my packages to the computer. I should note that occasionally I get a message from Windows"(Windows firewall defender has blocked some features of R for Windows GUI front-end on all public and private networks". Do you have any suggestions?

**Comment by doserjef** [comment]
Hi @swbigelow, 

Thanks for the note. I'm not very familiar with parallelization on Windows systems, but it does seem like this could be happening as a result of the windows firewall on your machine (i.e., take a look at [this guide](https://search.r-project.org/CRAN/refmans/enmSdmX/html/troubleshooting_parallel_operations.html)). Are you running `spPGOcc()` with cross-validation (i.e., are you specifying the `k.fold` argument?). Cross-validation is the only time that that the `doParallel` package is used, so I'm thinking that you should be able to run the functions without specifying that argument. 

Thanks,

Jeff

**Comment by swbigelow** [comment]
I just ran spPGOcc() without cross-validation (k-fold argument) and it ran like a charm, no more '.doSnowGlobals' error message. I have now Bayesed! It's exciting. Thanks very much for the troubleshooting help. I look forward to running this package for black rail and Bachmann's sparrow.

**Comment by doserjef** [comment]
Awesome! Glad to hear you got it to run!
