### ISSUE TITLE
extracting predicted occupancy state

### ISSUE THREAD

**Issue by dvpopescu** [doserjef/spOccupancy#46]
hi Jeff,

I am using msPGocc with a metagenomics eDNA dataset with 101 sites and 157 species. Many species, some very common ones, are only detected at only a handful of sites. 
I need to get detection-corrected occupancy predictions for these species at the same sampling locations, rather than at new locations. Since function _predict_ requires new locations, would using function _fitted_ be appropriate in this case? Thank you!

Viorel

**Comment by doserjef** [comment]
Hi Viorel, 

Thanks for the note! `fitted()` is for extracting the detection probability values as well as "replicate" data values for use with posterior predictive checks, which I don't think is what you're looking for here. Instead, the detection corrected occupancy predictions at the same sampling locations are available directly in the model output object. So, if you saved the output from `msPGOcc` in a file called `out`, you can access the posterior samples for the detection corrected occupancy probabilities with `out$psi.samples` or you can get the posterior samples for the latent occupancy state (the binary 0/1 value) with `out$z.samples`. 

Hope that helps! Let me know if I can clarify anything. 

Jeff

**Comment by dvpopescu** [comment]
Thank you, Jeff!
