### ISSUE TITLE
 'n.chains' is not an argument

### ISSUE THREAD

**Issue by Xuletajr** [doserjef/spOccupancy#5]
Dear Doser,

First of all, congratulations for the package, it is impressive and very useful. I'd like to fit some single-species occupancy models (both spatial and non-spatial), however I am facing some issues. I am trying to set the number of chains using "n.chains" argument (n.chains = 3), but both "spPGOcc" and "PGOcc" are returning a warning message:  'n.chains' is not an argument. Additionally, Rhat values and ESS values are not being shown when I use the summary for the output. Lastly, the posterior predictive checks ("ppcOcc") is not working for my output. 

Best

**Comment by doserjef** [comment]
Hi José, 

Thanks for reaching out and for the kind words. I am pretty sure the first couple of errors with the missing "n.chains" argument and missing Rhat and ESS values is a result of the version of spOccupancy you have downloaded. I added in those features in version 0.2.0, so try doing a fresh install of spOccupancy v0.2.1 from CRAN with `install.packages("spOccupancy")` and I'm thinking that will fix those problems, but let me know if that doesn't fix it. I'm not quite sure what's going on with the posterior predictive checks, but try it out again after installing the latest version and see if you get the same error. If you still get the error, feel free to post the error you get here and we can figure out what's going on. 

Cheers,

Jeff

**Comment by Xuletajr** [comment]
Hi Jeff,

thank you very much for your reply. I updated the package and the first couple of error were fixed. But, I am still facing some issues for performing posterior predictive checks. I close the present issue and open a new one.
