### ISSUE TITLE
Random slopes in occupancy model

### ISSUE THREAD

**Issue by zwallac2** [doserjef/spOccupancy#6]
Hi Jeff,

Thanks for developing this package. I think it is a tremendous contribution that will open up these types of models up to many more users.

Apologies if this is not the correct forum to ask a question about the package. I am wondering if it is possible to fit random slopes and intercepts in spOccupancy using lme4-type syntax (e.g., ~ContinuousCovariate + (ContinuousCovariate|GroupingFactor)). While exploring the package, I tried that random effects structure on occupancy in a single-species occupancy model with PGOcc and got the following error:

Error in X.re[, j] <- as.vector(re.terms$Ztlist[[j]]@i) : 
  number of items to replace is not a multiple of replacement length

Random intercepts worked fine for multiple factors (e.g., ~(1|GroupingFactorA) + (1|GroupingFactorB)), but the error made me wonder if random slopes are not currently supported.

Thanks for any information you can provide!

Zach

**Comment by doserjef** [comment]
Hi Zach, 

Thanks for reaching out and for the kind words. Yes, unfortunately spOccupancy does not currently support random slopes. It's on my todo list for sometime this year to add in that functionality, but for now it only supports random intercepts. You can fit random intercepts in both the occupancy and detection portions of the model for non-spatial models, and currently can only fit random intercepts in the detection portion for spatial occupancy models. I'm currently adding in functionality for random intercepts in the occupancy portion of spatial models as well, and am planning to get that update to CRAN within the next 3 weeks or so. I'll also point out that I found a bug when performing cross-validation with models that have random intercepts, so if you're planning to do any sort of model comparison/selection with random intercepts I'll encourage you to use the `waicOcc` function for now. That bug will also be updated on CRAN in the next few weeks. 

Let me know if you have any other questions. Feel free to post again here or shoot me an email (doserjef@msu.edu) if that's easier. 

Kind regards, 

Jeff

**Comment by zwallac2** [comment]
Thanks, Jeff. Looking forward to that added functionality, as well as other combinations of features that might be on your list, like multi-species integrated models.

Keep up the good work!

Zach
